### ISSUE TITLE
inconsistent arguments are passed to the listener

### ISSUE THREAD

**Issue by Eluminati** [sindresorhus/on-change#63]
Hi again... 🙈

I have recognized that different arguments are passed to the listener when I modify an array with a method like `splice` or assign a value with a key `array[key] = value`.

in case of the method, the whole object is passed to the listener and in case of the assignment only the assigned value is passed to the listener.

The behavior should always be the same. In my opinion it is perfect to always get the whole object before and after. In this case it is always possible to compare those objects.

Maybe this could be optional? Benefit: downwards compatibility.

**Comment by DarrenPaulWright** [comment]
> The behavior should always be the same. In my opinion it is perfect to always get the whole object before and after. In this case it is always possible to compare those objects.

I would argue that the behavior is the same. When calling a method you are acting on the object (potentially with multiple property changes), but when you are changing a property value directly you are acting on that value. If I followed your logic to it's conclusion, we would only ever provide the original object passed in to onChange (which is already provided as `this` in the callback), since you are always modifying a property on that original object, no matter how deeply nested the change is. 

Originally onChange called the callback for every change that occurred within a method call, but you can imagine the pain when calling something like array.shift(), where the index of every element changes.

I would recommend in cases where you want to compare the parent object/array that you look at the path of the change and get the parent.
